export const STATIC_BRANDS = [
  { brand: "underarmor", img: "/images/brands/underarmour.png", link: "https://www.underarmour.com/en-ca?cid=PS%7cCA%7cBR%7cggl%7call%7cunderarmour+website%7call%7capp%7call%7cexact%7cdg%7cp38473539106&gclid=Cj0KCQjwxYLoBRCxARIsAEf16-uKlZXOJHYLC793SzmKAlJcfo0EbJdwI2Oa_aE8iM4Q2-CR5NNw9R0aAmZuEALw_wcB&gclsrc=aw.ds" },
  { brand: "ccmhockey", img: "/images/brands/ccmhockey.png", link: "https://ccmhockey.com" },
  { brand: "bauer", img: "/images/brands/bauer.png", link: "https://www.bauer.com" },
  { brand: "roots", img: "/images/brands/roots73.svg", link: "http://www.trimarksportswear.com/cgi-bin/triweb/site.w?location=mcopy.w&mcopy=st_roots_footer&frames=no&target=main&sponsor=000100" },
  { brand: "puma", img: "/images/brands/puma.svg", link: "http://www.trimarksportswear.com/cgi-bin/triweb/site.w?location=mcopy.w&mcopy=st_puma_footer&frames=no&target=main&sponsor=000100" },
  { brand: "nike", img: "/images/brands/nike.png", link: "https://www.technosport.com/catalog/Brands/Nike/" },
  { brand: "newera", img: "/images/brands/newera.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/new-era-reg.html" },
  { brand: "americanapparel", img: "/images/brands/americanapparel.png", link: "https://www.technosport.com/catalog/Brands/American-Apparel/" },
  { brand: "newbalance", img: "/images/brands/newbalance.png", link: "https://www.technosport.com/catalog/Brands/New-Balance/" },
  { brand: "dryframe", img: "/images/brands/dryframe.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/dryframe-174.html" },
  { brand: "coalharbour", img: "/images/brands/ch.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/coal-harbour-reg.html" },
  { brand: "atc", img: "/images/brands/atc.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/atc-153.html" },
  { brand: "esactive", img: "/images/brands/esactive.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/es-active-reg.html" },
  { brand: "everyday", img: "/images/brands/everyday.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/everyday-reg-collection.html" },
  { brand: "eurospun", img: "/images/brands/eurospun.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/eurospun.html" },
  { brand: "koi", img: "/images/brands/koi.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/koi-174.html" },
  { brand: "thenorthface", img: "/images/brands/thenorthface.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/the-north-face-reg.html" },
  { brand: "flexfit", img: "/images/brands/flexfit.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/atc-153-by-flexfit-174.html" },
  { brand: "yupoong", img: "/images/brands/yupoong.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/yupoong-174.html" },
  { brand: "ogio", img: "/images/brands/ogio.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/ogio-174.html" },
  { brand: "callaway", img: "/images/brands/callaway.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/callaway-174.html" },
  { brand: "eddiebauer", img: "/images/brands/eb.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/eddie-bauer.html" },
  { brand: "gildan", img: "/images/brands/gildan.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/gildan-reg.html" },
  { brand: "fruitoftheloom", img: "/images/brands/fol.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/fruit-of-the-loom-174.html" },
  { brand: "redkap", img: "/images/brands/redkap.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/red-kap-174.html" },
  { brand: "realtree", img: "/images/brands/realtree.png", link: "https://www.sanmarcanada.com/shop-catalogue/shop-by-brand/realtree-174.html" },
  { brand: "allsport", img: "/images/brands/allsport.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:All%20Sport" },
  { brand: "allstyle", img: "/images/brands/alstyle.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Alstyle" },
  { brand: "alternative", img: "/images/brands/alternative.jpg", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Alternative" },
  { brand: "ashcity", img: "/images/brands/ashcity.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Ash%20City" },
  { brand: "ashcityim", img: "/images/brands/ashcityim.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Ash%20City%20-%20Il%20Migliore" },
  { brand: "bellacanvas", img: "/images/brands/bellacanvas.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Bella%20%2B%20Canvas" },
  { brand: "champion", img: "/images/brands/champion.jpg", link: "https://www.technosport.com/catalog/Brands/Champion/" },
  { brand: "codefive", img: "/images/brands/codefive.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Code%20Five" },
  { brand: "columbia", img: "/images/brands/columbia.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Columbia" },
  { brand: "dickies", img: "/images/brands/dickies.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Dickies" },
  { brand: "dickiesdropship", img: "/images/brands/dropship.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Dickies%20Drop%20Ship" },
  { brand: "driduck", img: "/images/brands/driduck.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Dri%20Duck" },
  { brand: "gemline", img: "/images/brands/gemline.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Gemline" },
  { brand: "jerzees", img: "/images/brands/jerzees.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Jerzees" },
  { brand: "marmot", img: "/images/brands/marmot.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Marmot" },
  { brand: "nextlevel", img: "/images/brands/nextlevel.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Next%20Level" },
  { brand: "rabbitskins", img: "/images/brands/rabbitskins.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Rabbit%20Skins" },
  { brand: "spyder", img: "/images/brands/spyder.jpg", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Spyder" },
  { brand: "threadfast", img: "/images/brands/threadfast.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Threadfast" },
  { brand: "tie-dye", img: "/images/brands/tiedye.webp", link: "https://www.alphabroder.ca/cgi-bin/online/webshr/search-result.w?ref=Mill_Name:Tie-Dye" },
  { brand: "elevate", img: "/images/brands/elevate.svg", link: "http://www.trimarksportswear.com/cgi-bin/triweb/site.w?location=mcopy.w&mcopy=st_elevate_footer&frames=no&target=main&sponsor=000100" },
  { brand: "highsierra", img: "/images/brands/highsierra.svg", link: "http://www.trimarksportswear.com/cgi-bin/triweb/site.w?location=mcopy.w&mcopy=st_HighSierra_footer&frames=no&target=main&sponsor=000100" },
  { brand: "lacoste", img: "/images/brands/lacoste.png", link: "https://www.technosport.com/catalog/Brands/Lacoste/" },
  { brand: "oakley", img: "/images/brands/oakley.png", link: "https://www.technosport.com/catalog/Brands/Oakley/" },
  { brand: "levelwear", img: "/images/brands/levelwear.png", link: "https://ca.levelwear.com/" },
  { brand: "kewl", img: "/images/brands/kewl.png", link: "https://ca.levelwearteam.com/" },
  { brand: "cutter&buck", img: "/images/brands/cutter&buck.webp", link: "https://cutterbuck.com/" }
];

{/* check correct link for kewl?
    also a couple of newly added brands,
    bicgraphic,
    fersten,
    knpheadwear,
    spector&co,
    starline,
    stormtech
*/}